### ISSUE TITLE
Transfer mongoid-geospatial to github.com/mongoid

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-geospatial#48]
I had https://github.com/mongoid kindly donated to the community by the nice folks at MongoDB. The three people who have org level admin access are currently @durran, @estolfo and myself. 

I want to invite this project to be moved to the org. I think it makes good sense to group mongoid projects together and have continuous support from MongoDB, the company, over the long term. All admins of this project will continue having admin access of course, but this would reduce the bus factor since currently only @nofxx can add maintainers here. 

If you think it's a good idea, please transfer this project to me and I'll move it into the org and please add `dblock@dblock.org`, `emily@mongodb.com` and `durran@gmail.com` to rubygems.

**Comment by nofxx** [comment]
@dblock, that's great... actually talked to durran years ago about a namespace for all gems.
Rubygems np, but how about this repo? I mean, it's a fork...
Do you think it's better to move it or create a new?

**Comment by dblock** [comment]
You have issues here and permissions, I'd rather transfer than fork. We probably should orphan the parent, but that's another story.

**Comment by nofxx** [comment]
Rubygems done. Need admin rights in mongoid to transfer repo.

**Comment by dblock** [comment]
@nofxx transfer it to me and I'll move it?

**Comment by dblock** [comment]
Now at https://github.com/mongoid/mongoid-geospatial, thanks! @nofxx is admin on it. Party on (needs links changes, etc.).
