### ISSUE TITLE
Expand the maintenance team for this gem

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-geospatial#54]
Maybe @nofxx can try and involve some of the people that were recently making pull requests and who are actively using this gem?

**Comment by nofxx** [comment]
Need to give it more love, will do this year.
Also yah, motivate and involve ppl, that's a social skill I need to improve ;) hehe

**Comment by dblock** [comment]
@nofxx Do you want me to try and coerce some other people into maintainers here? Now that I am using this library actively I am happy to do some grooming around the project's issues and PRs and see who can contribute - if you're OK with me running with it?

**Comment by nofxx** [comment]
Hello @dblock, just added you as admin, thanks!

**Comment by dblock** [comment]
Thanks, I'll try to take care of some open PRs and issues. But feel free to not let me and step in @nofxx  :)

**Comment by dblock** [comment]
On it.
