### ISSUE TITLE
Use LatLong instead of LongLat

### ISSUE THREAD

**Issue by ramonmacias** [mongoid/mongoid-geospatial#61]
So this is a mistake for this gem, the ISO 6709 defines that always Longitude must be before than Latitude, so please you should follow this convention in order to avoid problems with sync with clients

**Comment by ramonmacias** [comment]
visit this link http://matsp888.no-ip.org/~mats/Text/GIS/ISO_FDIS%206709.pdf on the section 6.4 part a) defines the order of this values

**Comment by dblock** [comment]
If you want to contribute a fix, please do. It will need a major version bump, an UPGRADING document of how to deal with it, etc.

**Comment by dblock** [comment]
See https://github.com/mongoid/mongoid-geospatial/pull/64 for a proposed solution.

**Comment by dblock** [comment]
I merged #64.
